# syntax=dhi.io/build:2-alpine3.23

name: FrankenPHP
image: ghcr.io/kenshodigital/frankenphp
variant: dev
tags:
  - 1-php8.5-alpine3.23-dev
  - 1-php8.5.${PHP_VERSION_PATCH}-alpine3.23-dev
  - 1.${FRANKENPHP_VERSION_MINOR}-php8.5-alpine3.23-dev
  - 1.${FRANKENPHP_VERSION_MINOR}-php8.5.${PHP_VERSION_PATCH}-alpine3.23-dev
  - 1.${FRANKENPHP_VERSION_MINOR}.${FRANKENPHP_VERSION_PATCH}-php8.5-alpine3.23-dev
  - 1.${FRANKENPHP_VERSION_MINOR}.${FRANKENPHP_VERSION_PATCH}-php8.5.${PHP_VERSION_PATCH}-alpine3.23-dev

platforms:
  - linux/amd64
  - linux/arm64

dates:
  release: ${RELEASE_DATE}

vars:
  RELEASE_DATE: ${RELEASE_DATE}
  FRANKENPHP_PACKAGE_VERSION: ${FRANKENPHP_PACKAGE_VERSION}
  PHP_PACKAGE_VERSION: ${PHP_PACKAGE_VERSION}

contents:
  repositories:
    - https://dhi.io/apk/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/main
    - https://dl-cdn.alpinelinux.org/alpine/v3.23/community
    - https://pkg.henderkes.com/api/packages/85/alpine/main/php-zts
  keyring:
    - https://dhi.io/keyring/dhi-apk@docker-0F81AD7700D99184.rsa.pub
    - https://github.com/kenshodigital/frankenphp/raw/refs/heads/main/key/alpine/${KEYFILE}
  packages:
    - alpine-baselayout-data
    - apk-tools
    - busybox
    - ca-certificates-bundle
    - frankenphp
    - libgcc
    - php-zts-cli
    - php-zts-devel
    - php-zts-embed
    - php-zts-xdebug
    - pie-zts
    - tzdata
  files:
    - url: https://getcomposer.org/download/latest-stable/composer.phar
      checksum: sha256:${COMPOSER_CHECKSUM}
      path: /usr/local/bin/composer
      mode: "0755"

accounts:
  root: true
  run-as: root
  users:
    - name: frankenphp
      uid: 65532
      gid: 65532
  groups:
    - name: frankenphp
      gid: 65532
      members:
        - frankenphp

os-release:
  name: Docker Hardened Images (Alpine)
  id: alpine
  version-id: "3.23"
  pretty-name: Docker Hardened Images/Alpine Linux v3.23
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/

work-dir: /srv

environment:
  SERVER_NAME: :8080
  SERVER_ROOT: /srv/public
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

paths:
  - type: file
    path: /etc/frankenphp/Caddyfile
    content: |
      {
      	skip_install_trust
      }
      {$SERVER_NAME} {
      	root {$SERVER_ROOT}
      	encode zstd br gzip
      	php_server
      }
  - type: directory
    path: /srv/public
  - type: symlink
    path: /srv/public/index.php
    source: /usr/share/frankenphp/index.php

annotations:
  org.opencontainers.image.description: A minimal FrankenPHP image
  org.opencontainers.image.licenses: MIT

entrypoint:
  - /usr/bin/frankenphp

cmd:
  - run
  - --config
  - /etc/frankenphp/Caddyfile

ports:
  - 8080/tcp
