name: Rerun

on:
  workflow_dispatch:
    inputs:
      run_id:
        required: true

jobs:
  rerun:
    name: Rerun ${{ inputs.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Rerun failed jobs
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run watch ${{ inputs.run_id }} > /dev/null 2>&1
          gh run rerun ${{ inputs.run_id }} --failed
